// LoL Champion Recommender - Expanded Champion Database
// 100+ Most Popular Champions with Complete Data

const championDatabase = {
    // ASSASSINS
    'Ahri': { name: 'Ahri', title: 'the Nine-Tailed Fox', role: 'Assassin', difficulty: 5, tags: ['Mage', 'Assassin'], attributes: { damage: 8, toughness: 3, control: 6, mobility: 8, utility: 5 }, description: 'Innately connected to the latent power of Runeterra, Ahri is a vastaya who can reshape magic into orbs of raw energy.', abilities: [{ key: 'P', name: 'Essence Theft', description: 'Heals when damaging enemies with abilities.' }, { key: 'Q', name: 'Orb of Deception', description: 'Sends out and pulls back her orb, dealing magic and true damage.' }, { key: 'W', name: 'Fox-Fire', description: 'Releases three fox-fires that seek out nearby enemies.' }, { key: 'E', name: 'Charm', description: 'Charms and damages the first enemy hit.' }, { key: 'R', name: 'Spirit Rush', description: 'Dashes forward and fires essence bolts up to three times.' }], matchingFactors: { rolePreference: { 'Assassin': 10, 'Mage': 8 }, difficulty: { 'Moderate': 8, 'Hard': 9 }, gameplay: { 'Solo plays': 9, 'Roaming': 8, 'Team fights': 7 }, range: { 'Ranged': 9, 'No preference': 7 }, damage: { 'High': 9, 'Very High': 8 }, style: { 'Offensive': 9, 'Balanced': 7 }, abilities: { 'Burst Damage': 9, 'Mobility': 8 }, experience: { 'Intermediate': 8, 'Advanced': 9 }, motivation: { 'Having fun': 9, 'Improving skills': 8 } } },
    
    'Akali': { name: 'Akali', title: 'the Rogue Assassin', role: 'Assassin', difficulty: 7, tags: ['Assassin'], attributes: { damage: 8, toughness: 3, control: 4, mobility: 9, utility: 4 }, description: 'Abandoning the Kinkou Order, Akali now strikes alone as a deadly weapon.', abilities: [{ key: 'P', name: 'Assassin\'s Mark', description: 'Creates a ring around enemies hit by abilities.' }, { key: 'Q', name: 'Five Point Strike', description: 'Throws kunai in an arc, dealing damage.' }, { key: 'W', name: 'Twilight Shroud', description: 'Drops a smoke bomb, becoming invisible.' }, { key: 'E', name: 'Shuriken Flip', description: 'Throws a shuriken that can be reactivated to dash.' }, { key: 'R', name: 'Perfect Execution', description: 'Dashes through enemies, can be cast twice.' }], matchingFactors: { rolePreference: { 'Assassin': 10 }, difficulty: { 'Hard': 9, 'Expert': 8 }, gameplay: { 'Solo plays': 10, 'Roaming': 9 }, range: { 'Melee': 8, 'No preference': 6 }, damage: { 'High': 8, 'Very High': 9 }, style: { 'Offensive': 10, 'Balanced': 4 }, abilities: { 'Burst Damage': 9, 'Mobility': 10 }, experience: { 'Advanced': 9, 'Expert': 8 }, motivation: { 'Improving skills': 9, 'Winning games': 8 } } },
    
    'Diana': { name: 'Diana', title: 'Scorn of the Moon', role: 'Assassin', difficulty: 4, tags: ['Fighter', 'Mage'], attributes: { damage: 8, toughness: 6, control: 4, mobility: 7, utility: 4 }, description: 'Bearing her crescent moonblade, Diana fights as a warrior of the Lunari.', abilities: [{ key: 'P', name: 'Moonsilver Blade', description: 'Third basic attack cleaves nearby enemies.' }, { key: 'Q', name: 'Crescent Strike', description: 'Unleashes a bolt of lunar energy in an arc.' }, { key: 'W', name: 'Pale Cascade', description: 'Creates orbiting spheres that grant a shield.' }, { key: 'E', name: 'Lunar Rush', description: 'Teleports to an enemy and deals damage.' }, { key: 'R', name: 'Moonfall', description: 'Reveals and draws in all nearby enemies.' }], matchingFactors: { rolePreference: { 'Assassin': 9, 'Fighter': 8 }, difficulty: { 'Moderate': 9, 'Hard': 7 }, gameplay: { 'Solo plays': 8, 'Team fights': 9 }, range: { 'Melee': 9, 'No preference': 7 }, damage: { 'High': 9, 'Very High': 7 }, style: { 'Offensive': 9, 'Balanced': 7 }, abilities: { 'Burst Damage': 9, 'Sustained Damage': 6 }, experience: { 'Intermediate': 9, 'Advanced': 7 }, motivation: { 'Improving skills': 8, 'Having fun': 8 } } },
    
    'Ekko': { name: 'Ekko', title: 'the Boy Who Shattered Time', role: 'Assassin', difficulty: 8, tags: ['Assassin', 'Mage'], attributes: { damage: 8, toughness: 3, control: 7, mobility: 9, utility: 6 }, description: 'A prodigy from Zaun who manipulates time to his advantage.', abilities: [{ key: 'P', name: 'Z-Drive Resonance', description: 'Builds stacks on enemies for bonus damage.' }, { key: 'Q', name: 'Timewinder', description: 'Throws a temporal grenade that slows enemies.' }, { key: 'W', name: 'Parallel Convergence', description: 'Creates an anomaly that slows enemies and shields Ekko.' }, { key: 'E', name: 'Phase Dive', description: 'Dashes and next attack teleports to target.' }, { key: 'R', name: 'Chronobreak', description: 'Rewinds time, returning to previous position.' }], matchingFactors: { rolePreference: { 'Assassin': 10, 'Mage': 6 }, difficulty: { 'Hard': 9, 'Expert': 10 }, gameplay: { 'Solo plays': 10, 'Roaming': 8 }, range: { 'Melee': 8, 'No preference': 6 }, damage: { 'High': 8, 'Very High': 9 }, style: { 'Offensive': 9, 'Balanced': 7 }, abilities: { 'Burst Damage': 9, 'Mobility': 10 }, experience: { 'Advanced': 9, 'Expert': 10 }, motivation: { 'Improving skills': 10, 'Having fun': 8 } } },
    
    'Fizz': { name: 'Fizz', title: 'the Tidal Trickster', role: 'Assassin', difficulty: 6, tags: ['Assassin', 'Fighter'], attributes: { damage: 8, toughness: 4, control: 5, mobility: 9, utility: 4 }, description: 'An amphibious yordle who dwells among the reefs surrounding Bilgewater.', abilities: [{ key: 'P', name: 'Nimble Fighter', description: 'Takes reduced damage from basic attacks.' }, { key: 'Q', name: 'Urchin Strike', description: 'Dashes through target, dealing damage.' }, { key: 'W', name: 'Seastone Trident', description: 'Empowers attacks with magic damage over time.' }, { key: 'E', name: 'Playful / Trickster', description: 'Becomes untargetable, then slams down.' }, { key: 'R', name: 'Chum the Waters', description: 'Throws a fish that attracts a shark.' }], matchingFactors: { rolePreference: { 'Assassin': 10, 'Fighter': 6 }, difficulty: { 'Moderate': 7, 'Hard': 9 }, gameplay: { 'Solo plays': 10, 'Team fights': 7 }, range: { 'Melee': 9, 'No preference': 7 }, damage: { 'High': 8, 'Very High': 9 }, style: { 'Offensive': 10, 'Balanced': 5 }, abilities: { 'Burst Damage': 10, 'Mobility': 9 }, experience: { 'Intermediate': 7, 'Advanced': 9 }, motivation: { 'Having fun': 10, 'Winning games': 8 } } },
    
    'Katarina': { name: 'Katarina', title: 'the Sinister Blade', role: 'Assassin', difficulty: 8, tags: ['Assassin', 'Mage'], attributes: { damage: 9, toughness: 2, control: 4, mobility: 8, utility: 3 }, description: 'A Noxian assassin of the highest caliber.', abilities: [{ key: 'P', name: 'Voracity', description: 'Reduces cooldowns when enemies die.' }, { key: 'Q', name: 'Bouncing Blade', description: 'Throws a dagger that bounces between enemies.' }, { key: 'W', name: 'Preparation', description: 'Tosses a dagger into the air and gains movement speed.' }, { key: 'E', name: 'Shunpo', description: 'Instantly moves to a target.' }, { key: 'R', name: 'Death Lotus', description: 'Channels and rapidly throws daggers at nearby enemies.' }], matchingFactors: { rolePreference: { 'Assassin': 10, 'Mage': 6 }, difficulty: { 'Hard': 8, 'Expert': 10 }, gameplay: { 'Solo plays': 10, 'Team fights': 8 }, range: { 'Melee': 8, 'No preference': 6 }, damage: { 'Very High': 10, 'High': 8 }, style: { 'Offensive': 10, 'Balanced': 3 }, abilities: { 'Burst Damage': 10, 'Mobility': 9 }, experience: { 'Advanced': 8, 'Expert': 10 }, motivation: { 'Winning games': 9, 'Improving skills': 10 } } },
    
    'LeBlanc': { name: 'LeBlanc', title: 'the Deceiver', role: 'Assassin', difficulty: 9, tags: ['Assassin', 'Mage'], attributes: { damage: 8, toughness: 2, control: 6, mobility: 8, utility: 5 }, description: 'Mysterious even to other members of the Black Rose cabal.', abilities: [{ key: 'P', name: 'Mirror Image', description: 'Creates a clone when taking damage.' }, { key: 'Q', name: 'Sigil of Malice', description: 'Marks target for bonus damage.' }, { key: 'W', name: 'Distortion', description: 'Dashes to location, can return to original position.' }, { key: 'E', name: 'Ethereal Chains', description: 'Launches a chain that roots if target stays close.' }, { key: 'R', name: 'Mimic', description: 'Mimics one of her basic spells with enhanced effects.' }], matchingFactors: { rolePreference: { 'Assassin': 10, 'Mage': 8 }, difficulty: { 'Hard': 8, 'Expert': 10 }, gameplay: { 'Solo plays': 10, 'Roaming': 9 }, range: { 'Ranged': 8, 'No preference': 7 }, damage: { 'High': 8, 'Very High': 9 }, style: { 'Offensive': 10, 'Balanced': 5 }, abilities: { 'Burst Damage': 10, 'Mobility': 9 }, experience: { 'Advanced': 8, 'Expert': 10 }, motivation: { 'Improving skills': 10, 'Winning games': 9 } } },
    
    'Zed': { name: 'Zed', title: 'the Master of Shadows', role: 'Assassin', difficulty: 8, tags: ['Assassin'], attributes: { damage: 9, toughness: 2, control: 5, mobility: 8, utility: 4 }, description: 'Utterly ruthless and without mercy, Zed is the leader of the Order of Shadow.', abilities: [{ key: 'P', name: 'Contempt for the Weak', description: 'Basic attacks against low health enemies deal bonus damage.' }, { key: 'Q', name: 'Razor Shuriken', description: 'Zed and his shadows throw shurikens.' }, { key: 'W', name: 'Living Shadow', description: 'Creates a shadow that mimics abilities.' }, { key: 'E', name: 'Shadow Slash', description: 'Zed and shadows slash, dealing damage and slowing.' }, { key: 'R', name: 'Death Mark', description: 'Becomes untargetable and marks enemy for death.' }], matchingFactors: { rolePreference: { 'Assassin': 10 }, difficulty: { 'Hard': 8, 'Expert': 10 }, gameplay: { 'Solo plays': 10, 'Roaming': 8 }, range: { 'Melee': 8, 'No preference': 5 }, damage: { 'Very High': 10, 'High': 8 }, style: { 'Offensive': 10, 'Balanced': 4 }, abilities: { 'Burst Damage': 10, 'Mobility': 9 }, experience: { 'Advanced': 9, 'Expert': 10 }, motivation: { 'Winning games': 9, 'Improving skills': 10 } } }
};