#!/usr/bin/env python3
"""
Script to set up Supabase tables for the League of Legends Champion Recommender
"""

# Supabase configuration - replace with your actual values
SUPABASE_URL = "https://brshmbbohqcdseyirqsn.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyc2htYmJvaHFjZHNleWlycXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwOTYyNzAsImV4cCI6MjA3NjY3MjI3MH0.Yi-aWEuvArux0qRrEgnnzIljrsh5NnVBOxHlpBqbn2E"

def setup_supabase_tables():
    """Print instructions for setting up Supabase tables"""
    
    print("Setting up Supabase tables...")
    
    print("Users table schema:")
    print("- id (uuid, primary key, default: uuid_generate_v4())")
    print("- full_name (text)")
    print("- email (text)")
    print("- phone (text)")
    print("- age (integer)")
    print("- gender (text)")
    print("- experience (text)")
    print("- registration_date (timestamp with time zone, default: now())")
    print("- session_id (text, unique)")
    print()
    
    print("Questionnaire results table schema:")
    print("- id (uuid, primary key, default: uuid_generate_v4())")
    print("- session_id (text, foreign key to users.session_id)")
    print("- recommended_champion (text)")
    print("- winning_algorithm (text)")
    print("- confidence_score (numeric)")
    print("- random_forest_champion (text)")
    print("- random_forest_confidence (numeric)")
    print("- decision_tree_champion (text)")
    print("- decision_tree_confidence (numeric)")
    print("- knn_champion (text)")
    print("- knn_confidence (numeric)")
    print("- consensus_level (integer)")
    print("- user_answers (jsonb)")
    print("- completion_date (timestamp with time zone, default: now())")
    print("- pressure_response (text)")
    print("- aesthetic_preference (text)")
    print("- team_contribution (text)")
    print("- character_identity (text)")
    print("- problem_solving (text)")
    print()
    
    print("To create these tables in Supabase:")
    print("1. Go to your Supabase project dashboard")
    print("2. Navigate to Table Editor")
    print("3. Create the tables with the above schema")
    print()
    print("Alternatively, run these SQL commands in the SQL editor:")
    print()
    print("-- Create users table")
    print("create table users (")
    print("  id uuid default uuid_generate_v4() primary key,")
    print("  full_name text,")
    print("  email text,")
    print("  phone text,")
    print("  age integer,")
    print("  gender text,")
    print("  experience text,")
    print("  registration_date timestamp with time zone default now(),")
    print("  session_id text unique")
    print(");")
    print()
    print("-- Create questionnaire_results table")
    print("create table questionnaire_results (")
    print("  id uuid default uuid_generate_v4() primary key,")
    print("  session_id text references users(session_id),")
    print("  recommended_champion text,")
    print("  winning_algorithm text,")
    print("  confidence_score numeric,")
    print("  random_forest_champion text,")
    print("  random_forest_confidence numeric,")
    print("  decision_tree_champion text,")
    print("  decision_tree_confidence numeric,")
    print("  knn_champion text,")
    print("  knn_confidence numeric,")
    print("  consensus_level integer,")
    print("  user_answers jsonb,")
    print("  completion_date timestamp with time zone default now(),")
    print("  pressure_response text,")
    print("  aesthetic_preference text,")
    print("  team_contribution text,")
    print("  character_identity text,")
    print("  problem_solving text")
    print(");")

if __name__ == "__main__":
    setup_supabase_tables()